/**
 * 
 * Action type for reducer 
 * @author - NA 
 * @date - 5th May, 2024
 * 
 */
export const ActionTypes = {
    UPDATE_ORDER: 'UPDATE_ORDER', // WHEN USER CLICK UP AND DOWN BUTTON
    ADD_PROFILE: 'ADD_PROFILE', // WHEN USER CREATE NEW PROFILE
    RENAME_PROFILE: 'RENAME_PROFILE', // WHEN USER RENAME THE PROFILE NAME
    REMOVE_PROFILE: 'REMOVE_PROFILE', // WHEN USER REMOVE THE PROFILE
    ON_UPDATE_SELECTED_PROFILE: 'ON_UPDATE_SELECTED_PROFILE', // WHEN USER SELECT THE PROFILE BY CLICKING
    ON_UPDATE_EDIT_MODE: 'ON_UPDATE_EDIT_MODE', // WHEN USER TOGGLE BETWEEN EDIT MODE
    ON_UPDATE_DELETE_MODAL: 'ON_UPDATE_DELETE_MODAL' // WHEN USER TOGGLE BETWEEN DELETE MODAL POPUP
  };